version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  app:
    build: .
    container_name: microservicio_estudiantil_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - microservices-network
    restart: unless-stopped
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
    command: >
      sh -c "
        echo 'Iniciando microservicio estudiantil...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

networks:
  microservices-network:
    external: true

volumes:
  postgres_data: